language: node_js
node_js: '8'
cache: yarn
git:
  depth: 3
dist: trusty
sudo: false
env:
  global:
    - NODE_ENV=travisci
script:
- yarn build
- yarn prettier-ci
notifications:
  slack: webpurple:mFXgdAsg8h2xwQSK6JqX0gKL
