backend:
  name: github
  repo: kitos/web-purple
  branch: gatsby

media_folder: static/img
public_folder: /img

collections:
  - name: "event"
    label: "Event"
    folder: "src/pages/event"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "string"
      
      - label: "Date"
        name: "date"
        widget: "date"

      - label: "Speaker"
        name: "speaker"
        widget: "relation"
        collection: "speaker"
        searchFields: ["title"]
        valueField: "title"

  - name: "speaker"
    label: "Speaker"
    folder: "src/pages/speaker"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Fullname"
        name: "title"
        widget: "string"

      - label: "Avatar"
        name: "avatar"
        widget: "image"
