backend:
  name: github
  repo: kitos/web-purple
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "event"
    label: "Event"
    folder: "src/pages/event"
    extension: "yaml"
    create: true
    delete: false
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Description"
        name: "description"
        widget: "text"
      
      - label: "Date"
        name: "date"
        widget: "datetime"
        required: false

      - label: "Address"
        name: "address"
        required: false

      - label: "Talks"
        name: "talks"
        widget: "list"
        fields:
          - label: "Title"
            name: "title"

          - label: "Description"
            name: "description"
            widget: "text"

          - label: "Speaker"
            name: "speaker"
            widget: "relation"
            collection: "speaker"
            searchFields: ["title"]
            valueField: "title"

          - label: "Tags"
            name: "tags"
            widget: "list"

          - label: "Link to presentation"
            name: "presentation"
            widget: "string"
            required: false

      - label: "Social networks"
        name: "socialNetworks"
        required: false
        widget: "list"
        fields:
          - label: "Type"
            name: "type"
            widget: "select"
            options: ["vk", "fb"]

          - label: "Link"
            name: "link"
            type: "string"

      - label: "Link to video"
        name: "video"
        widget: "string"

  - name: "speaker"
    label: "Speaker"
    folder: "src/pages/speaker"
    extension: "yaml"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Fullname"
        name: "title"
        widget: "string"

      - label: "Avatar"
        name: "avatar"
        widget: "image"

      - label: "Organization"
        name: "organization"
        widget: "string"
        required: false

      - label: "Job position (title)"
        name: "jobTitle"
        widget: "string"
        required: false

      - label: "Social networks"
        name: "socialNetworks"
        required: false
        widget: "list"
        fields:
          - label: "Type"
            name: "type"
            widget: "select"
            options: ["vk", "fb", "twitter", "site"]

          - label: "Link"
            name: "link"
            type: "string"
